(require 'ert)
(require 'grc-lib)

(ert-deftest test-grc-list ()
  (should (equal '("hello") (grc-list "hello")))
  (should (equal '("hello") (grc-list '("hello")))))

(ert-deftest test-grc-string ()
  (should (string= "hello" (grc-string "hello")))
  (should (string= "123" (grc-string 123)))
  (should (string= "(123)" (grc-string '(123)))))

(ert-deftest test-grc-get-in ()
  (let ((alst '((a . "a")
                (b . ((c . "c")))
                (d . ((e . ((f . "f"))))))))
    (should (string= "a" (grc-get-in alst '(a))))
    (should (string= "c" (grc-get-in alst '(b c))))
    (should (string= "f" (grc-get-in alst '(d e f))))
    (should (eq nil (grc-get-in alst '(b z))))))
